title: NingjieLi
# Comment out url when working locally to resolve base urls correctly
url: https://Ningjie1.github.io/

# Owner/author information
owner:
  name: Ningjie1
  avatar: avatar.jpg
  email: ningjieli@csust.edu.cn
  github: Ningjie1
  linkedin: Ningjieli-
  scholar: https://scholar.google.com/citations?hl=en&user=zTZbYSEAAAAJ
  researchgate: https://www.researchgate.net/profile/Ningjie-Li/research?_tp=eyJjb250ZXh0Ijp7InBhZ2UiOiJwcm9maWxlIiwicHJldmlvdXNQYWdlIjpudWxsfX0

# https://search.google.com/search-console/ownership
google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# Links to include in top navigation
links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/
  - title: Beyond Research
    url: /hobbies/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai
future: true
highlighter: rouge

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
